services:
  vue:
    image: dan984/dockervue:0.1
    ports:
      - 8080:8080
    volumes:
      - ./target:/var/www/html
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "protected"
    ports: 
      - 5432:5432
    volumes:
      - /var/lib/mysql
volumes:
  data:
